doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

        dql:
            datetime_functions:
                date: Oro\ORM\Query\AST\Functions\SimpleFunction
                time: Oro\ORM\Query\AST\Functions\SimpleFunction
                timestamp: Oro\ORM\Query\AST\Functions\SimpleFunction
                convert_tz: Oro\ORM\Query\AST\Functions\DateTime\ConvertTz
            numeric_functions:
                timestampdiff: Oro\ORM\Query\AST\Functions\Numeric\TimestampDiff

